ALTER TABLE products ADD COLUMN IF NOT EXISTS latest_bill_photo_id VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS stockist_id UUID;
ALTER TABLE products ADD COLUMN IF NOT EXISTS has_flagged_bill BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_sellable BOOLEAN DEFAULT TRUE;
