ALTER TABLE stockists ADD COLUMN IF NOT EXISTS manual_closed BOOLEAN DEFAULT FALSE;
ALTER TABLE stockists ADD COLUMN IF NOT EXISTS closed_until TIMESTAMPTZ;
ALTER TABLE stockists ADD COLUMN IF NOT EXISTS closed_reason TEXT;
ALTER TABLE stockists ADD COLUMN IF NOT EXISTS payout_upi_id TEXT;
ALTER TABLE stockists ADD COLUMN IF NOT EXISTS payout_account_name TEXT;
ALTER TABLE stockists ADD COLUMN IF NOT EXISTS payout_bank_account TEXT;
ALTER TABLE stockists ADD COLUMN IF NOT EXISTS payout_ifsc TEXT;
ALTER TABLE stockists ADD COLUMN IF NOT EXISTS max_delivery_radius_km NUMERIC DEFAULT 5.0;
